---
title: "author_FinanzR"
author: "author"
date: "10. März 2015"
output: html_document
---

```{r encoding, echo=FALSE}
options(Encoding="UTF-8")
```

# Aufgabe 1

Download stocks

```{r stocks, echo=TRUE}
library(tseries)
library(timeDate)
library(MASS)
library(car)
library(zoo)
library(forecast)
library(fGarch)
library(copula)

# Load stocks
vow <- get.hist.quote(start="2006-01-01", instrument="vow.de", quote="AdjClose")
dai <- get.hist.quote(start="2006-01-01", instrument="dai.de", quote="AdjClose")

# Create returns
rvow <-diff(log(vow))
rdai <- diff(log(dai))

# Create list
rstocks <- list(rvow = rvow, rdai = rdai)
```

* Eigenschaften der univariaten unbedingten Verteilungen
```{r univunbvert}
options(scipen = 10)

sapply(rstocks, function(x) c(mean=mean(x), 
                              var = var(x),
                              skew = skewness(x),
                              kurt = kurtosis(x)))

layout(matrix(c(1,3,2,3), 2, 2, byrow = TRUE))
truehist(rvow)
qqPlot(rvow)
boxplot(coredata(rvow))
mtext("Return Volkswagen", outer = TRUE, side = 3, line = -3)

truehist(rdai)
qqPlot(rdai)
boxplot(coredata(rdai))
mtext("Return Daimler", outer = TRUE, side = 3, line = -3)

layout(1)
```

* Zeitliche Abhängigkeitsstruktur der Renditen und von Transformationen der Renditen
```{r}


par(mfrow = c(3, 1))
ts.plot(rvow)
title("Time Series Volkswagen")
ts.plot(abs(rvow))
ts.plot(rvow^2)

ts.plot(rdai)
title("Time Series Daimler")
ts.plot(abs(rdai))
ts.plot(rdai^2)

acf(rvow, na.action=na.pass, main = "")
title("ACF Volkswagen")
acf(abs(rvow), na.action=na.pass, main = "absolut")
acf(rvow^2, na.action=na.pass, main = "squared")

acf(rdai, na.action=na.pass, main = "")
title("ACF Daimler")
acf(abs(rdai), na.action=na.pass, main = "absolut")
acf(rdai^2, na.action=na.pass, main = "squared")

par(mfrow = c(1, 1))
```

* Abhängigkeiten zwischen den Renditen der beiden Aktien
```{r, warning=FALSE}
cor(rvow, rdai)
scatterplot(rdai,rvow)
ccf(as.numeric(rvow), as.numeric(rdai),  na.action = na.fail)

# Copula
q.rdai <- rank(as.numeric(rdai))/(length(as.numeric(rdai)) + 1)
q.rvow <- rank(as.numeric(rvow))/(length(as.numeric(rvow)) + 1)
plot(q.rdai, q.rvow)
```

* Wie können Sie zeitliche Schwankungen Abhängigkeitsstruktur diagnostizieren?
```{r, }
acf(rvow)
Box.test(rvow, lag=5, type="Ljung-Box")

acf(rdai)
Box.test(rdai, lag=5, type="Ljung-Box")
```

# Aufgabe 2

´auto.arima´

```{r autoarima}
(rvow_arima <- auto.arima(rvow, seasonal=FALSE, ic="bic"))
(rdai_arima <- auto.arima(rdai, seasonal = FALSE, ic = "bic"))


rvow_arima_res <- residuals(rvow_arima)
rdai_arima_res <- residuals(rdai_arima)

missings <- which(is.na(rvow_arima_res) | is.na(rdai_arima_res))

rvow_arima_res <- rvow_arima_res[-missings]
rdai_arima_res <- rdai_arima_res[-missings]

ts.plot(rvow_arima_res)
ts.plot(rdai_arima_res)


get_best_garch <- function(data){
  
  try_garch <- function(...){
    arguments <- list(...)
    tryCatch(do.call(garchFit, arguments), error = function(r) NA)
  }
  
  cond.dist <- c("norm", "snorm", "ged", "sged", "std", "sstd", "snig", "QMLE")
  delta <- c(1,2,3,4)
  
  param_set <- expand.grid(cond.dist, delta, stringsAsFactors = FALSE)
  
  garch_models <- mapply(FUN = try_garch, cond.dist = param_set$Var1, 
                         delta = param_set$Var2,
           MoreArgs = list(data = data, trace=FALSE))

  best_model <- which.min(lapply(garch_models, function(x) tryCatch(x@fit$ics[2], error = function(e) NA)))
  print(paste('best distribution: ', param_set[best_model, 1]))
  print(paste('with best delta: ', param_set[best_model, 2]))
  garchFit(data = data, cond.dist = param_set[best_model,1], 
           delta =  param_set[best_model, 2], trace = FALSE)
}


(rvow_garch <- get_best_garch(rvow_arima_res))
rvow_garch@fit$ics

ts.plot(rvow_arima_res, ylim=c(-.2,.2))
lines(quants <- qstd(.01, mean=rvow_garch@fit$par[1], sd=rvow_garch@sigma.t, 
                     nu = rvow_garch@fit$par[5]), col=2)
points(which(rvow_arima_res < quants), 
       rvow_arima_res[which(rvow_arima_res < quants)], pch=16, col=2)

sum(rvow_arima_res < quants)
sum(rvow_arima_res < quants)/length(rvow_arima_res)

(rdai_garch <- get_best_garch(rdai_arima_res))
rdai_garch@fit$ics

ts.plot(rdai_arima_res, ylim=c(-.2,.2))
lines(quants <- qged(.01, mean=rdai_garch@fit$par[1], sd=rdai_garch@sigma.t, 
                     nu = rdai_garch@fit$par[5]), col=2)
points(which(rdai_arima_res < quants), 
       rdai_arima_res[which(rdai_arima_res < quants)], pch=16, col=2)

sum(rdai_arima_res < quants)
sum(rdai_arima_res < quants)/length(rvow_arima_res)


oos_estimation <- function(data, model, dist, orig = 500, Tmax = 1000){
  k <- 1
  pars <- matrix(nrow=Tmax-orig, ncol=6, 
                 dimnames=list(NULL, c(names(model@fit$par),"sigma.t")))
  for(i in orig:(Tmax-1)){
    tryCatch({
          m <- garchFit(~ garch(1,1), data=as.data.frame(data[1:i]), trace=FALSE, 
                  cond.dist=dist)  
          p <- m@fit$par
          pars[k,1:5] <- p
          pars[k,6] <- p[2] + p[3]*data[i]^2 + p[4]*tail(m@sigma.t,1)
    }, error = function(e){
      print(paste("error in run: ", k))
      pars[k, ] <- NA
    }) 
    k <- k+1
  }
  pars
}

orig = 1500 
Tmax = 2000

parameters_rvow_garch <- oos_estimation(data = rvow_arima_res, 
                                        model = rvow_garch, dist = "std",
                                        orig = orig, Tmax = Tmax) 

plot(zoo(parameters_rvow_garch))


ts.plot(rvow_arima_res[(orig+1):Tmax])
lines(quants <- qstd(0.01, mean=parameters_rvow_garch[,1], sd=parameters_rvow_garch[,6], 
                     nu = parameters_rvow_garch[,5]), col = 2)
points(which(rvow_arima_res[(orig+1):Tmax] < quants), 
       rvow_arima_res[(orig+1):Tmax][which(rvow_arima_res[(orig+1):Tmax] < quants)], pch=16, col=2)

sum(rvow_arima_res[(orig+1):Tmax] < quants)
sum(rvow_arima_res[(orig+1):Tmax] < quants)/length(rvow_arima_res[orig+1:Tmax])

parameters_rdai_garch <- oos_estimation(data = rdai_arima_res, 
                                        model = rdai_garch, dist = "ged", 
                                        orig = orig, Tmax = Tmax)
                                         
plot(zoo(parameters_rdai_garch))

ts.plot(rdai_arima_res[(orig+1):Tmax])
lines(quants <- qged(0.01, mean=parameters_rdai_garch[,1], sd=parameters_rdai_garch[,6], 
                     nu = parameters_rdai_garch[,5]), col = 2)

points(which(rdai_arima_res[(orig+1):Tmax] < quants), 
       rdai_arima_res[(orig+1):Tmax][which(rdai_arima_res[(orig+1):Tmax] < quants)], pch=16, col=2)

sum(rdai_arima_res[(orig+1):Tmax] < quants)
sum(rdai_arima_res[(orig+1):Tmax] < quants)/length(rdai_arima_res[orig+1:Tmax])



garch_predictions <- t(replicate(10000, as.numeric(garchSim(
  spec = garchSpec(model = list(), cond.dist = "std"), n=10, n.start=11))))
  

par(mfrow = c(1,2))
for(i in i:10){
  truehist(garch_predictions[,i], main=paste("Step:", i), xlab = "", xlim=c(-0.04, 0.04))
  params <- fitdistr(garch_predictions[,i], "t")
  qqPlot(garch_predictions[,i], dist = "t", df = params$estimate[3])
}
par(mfrow = c(1,1))



```


# Aufgabe 3

```{r}
rvow_garch_res <- residuals(rvow_garch)
rvow_garch_quant <- rank(rvow_garch_res)/(length(rvow_garch_res)+1)

rdai_garch_res <- residuals(rdai_garch)
rdai_garch_quant <- rank(rdai_garch_res)/(length(rdai_garch_res)+1)

plot(rvow_garch_quant, rdai_garch_quant)

param_set <- expand.grid(family = c("norm", "t"), 
                         param = c(0.1,0.25,0.5,0.75,1), stringsAsFactors = FALSE)


ellipic_copulas <- cbind(param_set, 
                         BIC = mapply(FUN = function(family, param) 
                           BIC(fitCopula(ellipCopula(family = family, param = param ), 
          data = cbind(rvow_garch_quant, rdai_garch_quant))),
       family = param_set$family, param = param_set$param))


family = c("clayton", "frank", "amh", "gumbel", "joe")

archmCopula




```

